### ISSUE TITLE
Density only really works on a single click

### ISSUE THREAD

**Issue by juschu** [Kellojo/GameObject-Brush#6]
In general, the brush should not only work on a single click but also when you drag the mouse with a pressed button through the scene. But if you move your mouse just a little bit a big amount of objects is placed even with a very low setting for density.

I think the problem is that when you move your mouse every single mouse move event is calling the function that places the objects. So with every call, only a few objects are placed but this happens very often. This means it's basically impossible just to place objects in a low density without clicking over and over again. But you also have to be very careful that you really just click and don't click and move. If you move just a single pixel the "place objects" function is called again and at that point, the density will be at least double.

I think a setting like "draw distance" could help. It would mean "only place new objects again when I moved my mouse x units". This should be measured in the units inside of the scene and not screen pixels.
So with the mouse down event, you place the objects and save the global coordinates where you did that as a Vector3 in a variable like last_input_point . Then, with every mouse move event, you check if the distance between last_input_point and the potential next last_input_point is bigger or equal than draw_distance. If yes, you place objects and save a new Vector3 in last_input_point .

**Comment by Kellojo** [comment]
Hi Juschu,
Nice to see, you have found your way over to the GitHub repo and have even took the time to create the two issues, thank you ;)

I'll take a look at the described issues and hopefully fix them soon.

**Comment by Kellojo** [comment]
Hi Juschu,
I just fixed both issues described by you and submitted the new version to review by the asset store team. Thank you very much for reporting both issues here.
